user www-data;
worker_processes auto;
pid /var/run/nginx.pid;

events {
    worker_connections 1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;

    server {
        listen 80;
        server_name _;

        # Proxy vers mercure (tout le trafic, y compris /static)
        location / {
            proxy_pass         http://127.0.0.1:8000/;
            proxy_set_header   Host $host;
            proxy_set_header   X-Real-IP $remote_addr;
            proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header   X-Forwarded-Proto $scheme;
        }
        # Servir les fichiers statiques uploadés par l'utilisateur
        location /mercure/uploads {
            alias /home/charles/mercure-arena/uploads/;
            autoindex on;
        }
        # Proxy vers l'application squeue
        location /squeue {
            proxy_pass         http://127.0.0.1:8080/squeue;
            proxy_set_header   Host $host;
            proxy_set_header   X-Real-IP $remote_addr;
            proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header   X-Forwarded-Proto $scheme;
        }
    }
}