[release]
address = "hmn-genomique-p01"
secret_key = "bY8OwSqU5nTpN4ML15JjbPCkR7ovU3lQyAwDMH71nDI="
log_level = "normal"
max_blocking = 512
port = 8000
workers = 12
ident = "Mercure"
ip_header = "X-Real-IP"
keep_alive = 5
cli_colors = true
ctrlc = true

mercure_db = "sqlite://mercure.db"

template_dir = "/app/static/templates"
static_dir = "/app/static"
upload_dir = "/OPT/hermes/uploads"

pipeline_dir = "/home/charles/mercure-arena/OPT/pipelines"
jobs_dir = "/home/charles/mercure-arena/OPT/JOBS"

sequencers_dir = "/data/raw/sequenceurs"
analysis_dir = "/data/analysis"
