[default]
address = "127.0.0.1"
secret_key = "hLtkhUgxdZJffXn6+YjJL7E3z0OwPAnx92NUZy8mpCQ="
log_level = "normal"
max_blocking = 512
port = 8000
workers = 12
ident = "Mercure"
ip_header = "X-Real-IP"
keep_alive = 5
ctrlc = true


[debug]
mercure_db = "sqlite:///home/charles/mercure/mercure.db"

template_dir = "/home/charles/mercure/static/templates"
static_dir = "/home/charles/mercure/static"
upload_dir = "/home/charles/mercure-arena/uploads"
logs_dir = "/home/charles/mercure-arena/OPT/JOBS/LOGS"

pipeline_dir = "/home/charles/mercure-arena/OPT/pipelines"
jobs_dir = "/home/charles/mercure-arena/OPT/JOBS"

sequencers_dir = "/home/charles/mercure-arena/data/raw/sequenceurs"
analysis_dir = "/home/charles/mercure-arena/data/analysis"
ont_dir = "/home/charles/mercure-arena/data/raw/sequenceurs/GRIDION/output"

check_run_completed = "/home/charles/mercure/scripts/run-completed.sh"
post_run_script = "/home/charles/mercure/scripts/post-run-script.sh"
pipelines_repo_url = "http://127.0.0.1:3000/mercure/pipelines.git"

cli_colors = true

[release]
address = "10.169.192.26"
mercure_db = "sqlite:///OPT/mercure/mercure.db"

template_dir = "/static/templates"
static_dir = "/static"
upload_dir = "/OPT/mercure/uploads"
logs_dir = "/OPT/JOBS/LOGS"

pipeline_dir = "/OPT/pipelines"
jobs_dir = "/OPT/JOBS"

sequencers_dir = "/data/raw/sequenceurs"
analysis_dir = "/data/analysis"
ont_dir = "/data/raw/sequenceurs/GRIDION/output"

check_run_completed = "/OPT/mercure/run-completed.sh"
post_run_script = "/OPT/mercure/post-run-script.sh"
pipelines_repo_url = "http://gitea:3000/mercure/pipelines.git"
