[package]
name = "mercure-lib"
version = "0.1.0"
edition = "2024"

[dependencies]
rocket = { version = "0.5", features = ["secrets", "json"] }
sqlx = { version = "0.7", features = [
    "runtime-tokio-rustls",
    "sqlite",
    "time",
] }
bcrypt = "0.15"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.0", features = ["full"] }
time = { version = "0.3", features = ["serde"] }
thiserror = "1.0"
chrono = "0.4.42"
diacritics = "0.2.2"
rocket_dyn_templates = "0.2.0"
intersection = "1.0.0"
